// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6362ie9yxTjn6RFgstzU2PDHH2hiUDeA',
    appId: '1:923858989918:web:c8c4c3152ca22c526cd5cf',
    messagingSenderId: '923858989918',
    projectId: 'ditonton-be982',
    authDomain: 'ditonton-be982.firebaseapp.com',
    storageBucket: 'ditonton-be982.appspot.com',
    measurementId: 'G-4ZV57XXK74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtZMIpzPI863XDm63VoYQfMbnBkcAUlzc',
    appId: '1:923858989918:android:6eedecfac67075696cd5cf',
    messagingSenderId: '923858989918',
    projectId: 'ditonton-be982',
    storageBucket: 'ditonton-be982.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuAvXo5h2TMjN4zKqilsAwyrceKEWWL40',
    appId: '1:923858989918:ios:abf5f57b9c3414d36cd5cf',
    messagingSenderId: '923858989918',
    projectId: 'ditonton-be982',
    storageBucket: 'ditonton-be982.appspot.com',
    iosClientId: '923858989918-lhona29nig9u72t140mnaja58mvrljp7.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
